### ISSUE TITLE
awt/swing 好像没删干净

### ISSUE THREAD

**Issue by allenkey666** [fly9i/finalspeed#1]
还是报错，请大神看看。

root@5K:~/fs# jamvm -jar ./finalspeed.jar -b
System: linux 3.18.23
java.lang.reflect.InvocationTargetException
   at java.lang.reflect.VMMethod.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:327)
   at jamvm.java.lang.JarLauncher.main(JarLauncher.java:50)
Caused by: java.awt.AWTError: Cannot load AWT toolkit: gnu.java.awt.peer.gtk.GtkToolkit
   at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:607)
   at javax.swing.plaf.basic.BasicLookAndFeel.initialize(BasicLookAndFeel.java:1720)
   at javax.swing.UIManager.setLookAndFeel(UIManager.java:912)
   at javax.swing.UIManager.<clinit>(UIManager.java:245)
   at javax.swing.JLabel.updateUI(JLabel.java:536)
   at javax.swing.table.DefaultTableCellRenderer.updateUI(DefaultTableCellRenderer.java:119)
   at javax.swing.JLabel.<init>(JLabel.java:507)
   at javax.swing.JLabel.<init>(JLabel.java:429)
   at javax.swing.table.DefaultTableCellRenderer.<init>(DefaultTableCellRenderer.java:86)
   at javax.swing.table.JTableHeader.createDefaultRenderer(JTableHeader.java:893)
   at javax.swing.table.JTableHeader.initializeLocalVars(JTableHeader.java:1053)
   at javax.swing.table.JTableHeader.<init>(JTableHeader.java:666)
   at javax.swing.JTable.createDefaultTableHeader(JTable.java:2800)
   at javax.swing.JTable.initializeLocalVars(JTable.java:2672)
   at javax.swing.JTable.<init>(JTable.java:2637)
   at javax.swing.JTable.<init>(JTable.java:2546)
   at net.fs.client.MapRuleListTable.<init>(MapRuleListTable.java:26)
   at net.fs.client.ClientUI.<init>(ClientUI.java:124)
   at net.fs.client.FSClient.main(FSClient.java:26)
   at java.lang.reflect.VMMethod.invoke(Native Method)
   ...2 more
Caused by: java.lang.UnsatisfiedLinkError: Native library `gtkpeer' not found (as file`libgtkpeer.so') in gnu.classpath.boot.library.path and java.library.path
   at java.lang.Runtime.loadLibrary(Runtime.java:763)
   at java.lang.System.loadLibrary(System.java:671)
   at gnu.java.awt.peer.gtk.GtkToolkit.<clinit>(GtkToolkit.java:177)
   at java.lang.VMClass.forName(Native Method)
   at java.lang.Class.forName(Class.java:233)
   at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:583)
   ...21 more

**Comment by fly9i** [comment]
没有充分测试，我再去看一下，只在vps上试了。。

**Comment by allenkey666** [comment]
另外，请问大神能否用java 1.5重新编译一下，因为openwrt上的jamvm只支持到java 1.5，谢谢！！！

**Comment by fly9i** [comment]
我解决一下上面问题，一起看一下java 1.5 的兼容问题

**Comment by allenkey666** [comment]
非常感谢！

**Comment by fly9i** [comment]
新做了一个去处所有awt/swing的版本，java1.5目前编译完运行有问题，正在解决

https://github.com/fly9i/finalspeed/releases

**Comment by allenkey666** [comment]
运行后，好像pcap调用有问题。

root@5K:~/fs# jamvm -jar finalspeed.jar -b
System: linux 3.18.23
Exception in thread "Thread-1" java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-mipsel/libjnidispatch.so) not found in resource path ([file:/root/fs/finalspeed.jar])
   at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:778)
   at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:738)
   at com.sun.jna.Native.<clinit>(Native.java:131)
   at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
   at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:28)
   at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:24)
   at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:48)
   at net.fs.client.ClientUI$1.run(ClientUI.java:156)
????,????libpcap,??????tcp??
java.lang.reflect.InvocationTargetException
   at java.lang.reflect.VMMethod.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:327)
   at jamvm.java.lang.JarLauncher.main(JarLauncher.java:50)
Caused by: java.lang.NoClassDefFoundError: com/sun/jna/Pointer
   at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:28)
   at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:24)
   at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:48)
   at net.fs.cap.CapEnv.detectInterface(CapEnv.java:287)
   at net.fs.cap.CapEnv.initInterface(CapEnv.java:212)
   at net.fs.cap.CapEnv.init(CapEnv.java:105)
   at net.fs.rudp.Route.<init>(Route.java:117)
   at net.fs.client.MapClient.<init>(MapClient.java:103)
   at net.fs.client.ClientUI.<init>(ClientUI.java:194)
   at net.fs.client.FSClient.main(FSClient.java:26)
   at java.lang.reflect.VMMethod.invoke(Native Method)
   ...2 more

**Comment by huangya90** [comment]
关注 java1.5.
